name: deps

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule: [cron: "0 0 * * *"]

concurrency: deps-${{ github.head_ref || github.run_id }}

jobs:
    deny:
        name: deny
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: EmbarkStudios/cargo-deny-action@v1
              with:
                  command: check all
